/**
 * Lista oficial de Cursos de Graduação da UERJ
 * Fonte: https://www.uerj.br/ensino/cursos-de-graduacao/
 */

export const UERJ_COURSES_BY_AREA: Record<string, string[]> = {
  "Biomédico": [
    "Ciências Biológicas",
    "Ciências Biológicas - Zona Oeste",
    "Ciências Biológicas (Biotecnologia e Produção) - Zona Oeste",
    "Ciências Biológicas (Gestão Ambiental) - Zona Oeste",
    "Enfermagem",
    "Farmácia - Zona Oeste",
    "Fisioterapia",
    "Medicina",
    "Medicina - Cabo Frio",
    "Nutrição",
    "Odontologia",
  ],
  "Ciências Sociais": [
    "Administração",
    "Arqueologia",
    "Ciências Contábeis",
    "Ciências Econômicas",
    "Ciências Sociais",
    "Direito",
    "Filosofia",
    "História",
    "Relações Internacionais",
    "Serviço Social",
  ],
  "Educação e Humanidades": [
    "Artes Visuais",
    "Ciências Biológicas - São Gonçalo",
    "Cinema e Audiovisual (Licenciatura) - Duque de Caxias",
    "Educação Física",
    "Geografia (Licenciatura) - Duque de Caxias",
    "Geografia (Licenciatura) - São Gonçalo",
    "História - São Gonçalo",
    "História da Arte",
    "Jornalismo",
    "Letras",
    "Letras (Licenciatura) - São Gonçalo",
    "Matemática (Licenciatura) - Duque de Caxias",
    "Matemática (Licenciatura) - São Gonçalo",
    "Pedagogia",
    "Pedagogia - Duque de Caxias",
    "Pedagogia - São Gonçalo",
    "Psicologia",
    "Relações Públicas",
  ],
  "Tecnologia e Ciências": [
    "Arquitetura e Urbanismo",
    "Ciências Ambientais",
    "Ciências Atuariais",
    "Ciência da Computação",
    "Ciência da Computação - Zona Oeste",
    "Design",
    "Engenharia Ambiental e Sanitária",
    "Engenharia Cartográfica",
    "Engenharia Civil",
    "Engenharia de Computação - Nova Friburgo",
    "Engenharia de Energias Renováveis",
    "Engenharia de Materiais - Zona Oeste",
    "Engenharia de Produção",
    "Engenharia de Produção - Resende",
    "Engenharia de Produção - Zona Oeste",
    "Engenharia Elétrica",
    "Engenharia Mecânica",
    "Engenharia Mecânica - Nova Friburgo",
    "Engenharia Mecânica - Resende",
    "Engenharia Metalúrgica - Zona Oeste",
    "Engenharia Química",
    "Engenharia Química - Resende",
    "Estatística",
    "Física",
    "Geografia",
    "Geografia - Cabo Frio",
    "Geologia",
    "Matemática",
    "Oceanografia",
    "Química",
    "Tecnologia em Análise e Desenvolvimento de Sistemas - Zona Oeste",
    "Tecnologia em Construção Naval - Zona Oeste",
    "Turismo",
  ],
};

export const ALL_UERJ_COURSES: string[] = Object.values(UERJ_COURSES_BY_AREA).flat();
